### ISSUE TITLE
fatal error: mpirxx.h: No such file or directory

### ISSUE THREAD

**Issue by prvsousa** [bristolcrypto/SPDZ-2#2]
I'm trying to compile in Ubuntu 14.04 but I get the error: 

> g++   -g -Wextra -Wall -O3 -I. -pthread      '-DPREP_DIR="Player-Data/"' -maes -mpclmul -msse4.1 -mtune=native  -c -o Math/bigint.o Math/bigint.cpp
> In file included from Math/bigint.cpp:4:0:
> Math/bigint.h:10:20: fatal error: mpirxx.h: No such file or directory
>  #include <mpirxx.h>
>                     ^
> compilation terminated.
> make: **\* [Math/bigint.o] Error 1

When I try to make "make". Can you help me?

**Comment by rdragos** [comment]
Have you compiled MPIR library with the flag --enable-cxx (when running configure) ?

**Comment by prvsousa** [comment]
I'm not understanding how can I make the setup of this. The file "configure" does not exists.

**Comment by rdragos** [comment]
MPIR is a pre-requisite for SPDZ. First you have to download the library: http://mpir.org/downloads.html
Then install it using the steps from INSTALL file with the exception that you have to enter './configure --enable-cxx' instead of the usual './configure'.

**Comment by prvsousa** [comment]
Oh sorry, with the README here, I confused and I thought that ./configure was in the SPDZ-2. Thanks! And sorry :+1:

**Comment by fatemehajikarami** [comment]
I'm trying to run spdz.
first I have same problem (mpirxx.h: No such file or dir....)
I solved this problem, and ran "make -j" for spdz.
now what should i do to start?
Scripts/setup-online.sh , make these errors:
Scripts/setup-online.sh: line 33: /home/....../SPDZ-2-master/Scripts/../Fake-Offline.x: No such file or directory
dd: failed to open 'Player-Data/Private-Input-0': No such file or directory
dd: failed to open 'Player-Data/Private-Input-1': No such file or directory

How could I make these file or directories?

**Comment by mkskeller** [comment]
This looks like compilation hasn't been successful. What happens if you run make again?

**Comment by fatemehajikarami** [comment]
I've got another error too,
./Server.x: error while loading shared libraries: libmpirxx.so.8: cannot open shared object file: No such file or directory.

and I solve it by adding path...:
export LD_LIBRARY_PATH = $LD_LIBRARY_PATH:/usr/local/lib

now i can run server and 2 players, but another error again
i'm trying to solve this now :)

first terminal:
./Server.x 2 5000
Bound on port 4999
Waiting for player 0
Connected to player 0
Waiting for player 1
Connected to player 1
Player 0 started.
Player 0 is on machine TamannaPC5
Player 1 started.
Player 1 is on machine TamannaPC5

second terminal:
./Player-Online.x -pn 5000 0 tutorial
Sent 0 to localhost:4999
My Name = TamannaPC5
My number = 0
2 players
Player 0 is running on machine TamannaPC5
Player 1 is running on machine TamannaPC5
Bound on port 5000
loading params from: /home/hajikarami/Tools/SPDZ-2-master/Player-Data/2-128-40/Params-Data
terminate called after throwing an instance of 'file_error'
  what():  File Error : /home/hajikarami/Tools/SPDZ-2-master/Player-Data/2-128-40/Params-Data
Aborted (core dumped)

and the third one:
./Player-Online.x -pn 5000 1 tutorial
Sent 1 to localhost:4999
My Name = TamannaPC5
My number = 1
2 players
Player 0 is running on machine TamannaPC5
Player 1 is running on machine TamannaPC5
Bound on port 5001
loading params from: /home/hajikarami/Tools/SPDZ-2-master/Player-Data/2-128-40/Params-Data
terminate called after throwing an instance of 'file_error'
  what():  File Error : /home/hajikarami/Tools/SPDZ-2-master/Player-Data/2-128-40/Params-Data
Aborted (core dumped)

**Comment by rdragos** [comment]
This looks like you haven't run the setup-online script before executing Player-Online.x.

**Comment by fatemehajikarami** [comment]
oh yeah, thanks
my problem with SPDZ is that i cant find out how to use it,
for example if i want to add tow number in MPC format, what should i do?
you know, I need more documentation about spdz structure to know how to use it and how to use it to write my own application and ....
I'm still confused with the structure and ...

**Comment by rbkhmrcr** [comment]
@fatemehajikarami 
There is an example in [tutorial.md](https://github.com/bristolcrypto/SPDZ-2/blob/0428462ab2c7e23db092e8df19ad958307715a36/tutorial.md) for how to add two numbers across two parties, I'm trying to add to the documentation as I go along with this and then I'll submit a pull request!
But for now I'm actually getting the same  `./Math/bigint.h:10:20: fatal error: mpirxx.h: No such file or directory` as you did -- how did you solve it?
Thanks :)

**Comment by rbkhmrcr** [comment]
Oh, solved it, doh -- `make install` on mpir failed, but `sudo make install` succeeded.

**Comment by prvsousa** [comment]
@rebekah93 mpir is a pre-requisit. You have to install it and then you enter  './configure --enable-cxx'

**Comment by fatemehajikarami** [comment]
Did you install SPDZ?
Could you use it?
I'm confused.
if  you have more experience, i am eager to hear from you :)

**Comment by prvsousa** [comment]
@fatemehajikarami  what is your problem ?

**Comment by songlinfan** [comment]
@prvsousa hi, I met this problem same as yours today, I can't install MPIR library in ubuntu . I run a docker container(ubuntu) to excu SCALE-MAMBA what is improvement  from SPDZ, there's a lot setback for me. I just wonder if you remember how to do it. could you reply me ? (my English is poor sorry)

**Comment by songlinfan** [comment]
I don't know why I can't access this URL http://www.mpir.org/downloads.html to download MPIR library.

**Comment by rdragos** [comment]
Hy @songlinfan, better to use MP-SPDZ: https://github.com/data61/MP-SPDZ
